# Generated by Django 6.1.1 on 2026-09-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_paid_course_alter_payment_paid_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('canceled', 'Оплата отменена')], default='pending', max_length=20, verbose_name='Статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID цены Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID продукта Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сессии Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счёт'), ('stripe', 'Stripe')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
